name    'ghoneycutt-utils'
version '2.0.1'
source 'git://github.com/ghoneycutt/puppet-module-utils.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage utils'
description 'Ensure arbitrary list of utility packages is present'
project_page 'https://github.com/ghoneycutt/puppet-module-utils'
